org: maferlazon
service: api-s3

provider:
  name: aws
  runtime: python3.13
  memorySize: 256 # default for functions (puede ajustarse por funci√≥n)
  timeout: 20
  iam:
    role: arn:aws:iam::873956399712:role/LabRole

functions:
  # --- YA EXISTENTES ---
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 1024
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda

  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda

  # --- NUEVAS FUNCIONES DEL EJERCICIO ---
  crear_bucket:
    handler: create_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/crear
          method: post
          cors: true
          integration: lambda

  crear_directorio:
    handler: create_directory.lambda_handler
    events:
      - http:
          path: /s3/bucket/crear-directorio
          method: post
          cors: true
          integration: lambda

  subir_archivo:
    handler: upload_file.lambda_handler
    events:
      - http:
          path: /s3/bucket/subir-archivo
          method: post
          cors: true
          integration: lambda